# Generated by Django 2.2.15 on 2021-02-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consent_user_information", "0002_consentuserinformation_os"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentuserinformation",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
