# Generated by Django 2.2.24 on 2021-07-01 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("consent_user_information", "0003_consentuserinformation_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentuserinformation",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
